"use client"

import type { ThemeConfig } from "./themes"

export interface ExportOptions {
  format: "tailwind" | "css" | "react" | "figma" | "zip"
  includeComponents?: boolean
  includeDocumentation?: boolean
  watermark?: boolean
}

export interface ExportResult {
  id: string
  name: string
  format: string
  content: string
  downloadUrl?: string
  size: string
  createdAt: string
}

export class ExportGenerator {
  static generateTailwindConfig(theme: ThemeConfig, options: ExportOptions): string {
    const config = {
      theme: {
        extend: {
          colors: theme.tokens.colors,
          fontFamily: {
            sans: theme.tokens.fonts.sans.split(",").map((f) => f.trim()),
            mono: theme.tokens.fonts.mono.split(",").map((f) => f.trim()),
            ...(theme.tokens.fonts.display && {
              display: theme.tokens.fonts.display.split(",").map((f) => f.trim()),
            }),
          },
          spacing: theme.tokens.spacing,
          borderRadius: {
            DEFAULT: theme.tokens.borderRadius,
          },
          boxShadow: theme.tokens.shadows,
        },
      },
    }

    const watermarkComment = options.watermark
      ? `// Generated by ThemeVault - Upgrade to remove watermark\n// Theme: ${theme.name}\n\n`
      : `// Generated by ThemeVault\n// Theme: ${theme.name}\n\n`

    return watermarkComment + `module.exports = ${JSON.stringify(config, null, 2)};`
  }

  static generateCSS(theme: ThemeConfig, options: ExportOptions): string {
    const watermarkComment = options.watermark
      ? `/* Generated by ThemeVault - Upgrade to remove watermark */\n/* Theme: ${theme.name} */\n\n`
      : `/* Generated by ThemeVault */\n/* Theme: ${theme.name} */\n\n`

    let css = watermarkComment

    css += `:root {\n`

    // Colors
    Object.entries(theme.tokens.colors).forEach(([key, value]) => {
      css += `  --${key}: ${value};\n`
    })

    // Fonts
    css += `  --font-sans: ${theme.tokens.fonts.sans};\n`
    css += `  --font-mono: ${theme.tokens.fonts.mono};\n`
    if (theme.tokens.fonts.display) {
      css += `  --font-display: ${theme.tokens.fonts.display};\n`
    }

    // Spacing
    Object.entries(theme.tokens.spacing).forEach(([key, value]) => {
      css += `  --spacing-${key}: ${value};\n`
    })

    // Border radius
    css += `  --radius: ${theme.tokens.borderRadius};\n`

    // Shadows
    Object.entries(theme.tokens.shadows).forEach(([key, value]) => {
      css += `  --shadow-${key}: ${value};\n`
    })

    css += `}\n\n`

    // Theme-specific classes
    css += `.theme-${theme.id} {\n`
    css += `  font-family: var(--font-sans);\n`
    css += `}\n`

    return css
  }

  static generateReactComponents(theme: ThemeConfig, options: ExportOptions): string {
    const watermarkComment = options.watermark
      ? `// Generated by ThemeVault - Upgrade to remove watermark\n// Theme: ${theme.name}\n\n`
      : `// Generated by ThemeVault\n// Theme: ${theme.name}\n\n`

    return (
      watermarkComment +
      `import React from 'react';

export const ${theme.name.replace(/\s+/g, "")}Theme = {
  colors: ${JSON.stringify(theme.tokens.colors, null, 2)},
  fonts: ${JSON.stringify(theme.tokens.fonts, null, 2)},
  spacing: ${JSON.stringify(theme.tokens.spacing, null, 2)},
  borderRadius: "${theme.tokens.borderRadius}",
  shadows: ${JSON.stringify(theme.tokens.shadows, null, 2)},
};

export const ThemeProvider = ({ children }: { children: React.ReactNode }) => {
  React.useEffect(() => {
    const root = document.documentElement;
    
    // Apply theme tokens
    ${Object.entries(theme.tokens.colors)
      .map(([key, value]) => `root.style.setProperty('--${key}', '${value}');`)
      .join("\n    ")}
    
    root.style.setProperty('--font-sans', '${theme.tokens.fonts.sans}');
    root.style.setProperty('--font-mono', '${theme.tokens.fonts.mono}');
    ${theme.tokens.fonts.display ? `root.style.setProperty('--font-display', '${theme.tokens.fonts.display}');` : ""}
    
    ${Object.entries(theme.tokens.spacing)
      .map(([key, value]) => `root.style.setProperty('--spacing-${key}', '${value}');`)
      .join("\n    ")}
    
    root.style.setProperty('--radius', '${theme.tokens.borderRadius}');
    
    ${Object.entries(theme.tokens.shadows)
      .map(([key, value]) => `root.style.setProperty('--shadow-${key}', '${value}');`)
      .join("\n    ")}
  }, []);

  return <div className="theme-${theme.id}">{children}</div>;
};`
    )
  }

  static generateFigmaLink(theme: ThemeConfig): string {
    // In a real app, this would generate actual Figma files
    return `https://figma.com/community/file/themevault-${theme.id}`
  }

  static async generateExport(theme: ThemeConfig, options: ExportOptions): Promise<ExportResult> {
    let content = ""
    let name = ""

    switch (options.format) {
      case "tailwind":
        content = this.generateTailwindConfig(theme, options)
        name = `${theme.id}-tailwind.config.js`
        break
      case "css":
        content = this.generateCSS(theme, options)
        name = `${theme.id}-theme.css`
        break
      case "react":
        content = this.generateReactComponents(theme, options)
        name = `${theme.id}-components.tsx`
        break
      case "figma":
        content = this.generateFigmaLink(theme)
        name = `${theme.id}-figma-link.txt`
        break
      case "zip":
        // Generate multiple files and zip them
        const tailwind = this.generateTailwindConfig(theme, options)
        const css = this.generateCSS(theme, options)
        const react = this.generateReactComponents(theme, options)

        content = JSON.stringify({
          "tailwind.config.js": tailwind,
          "theme.css": css,
          "components.tsx": react,
          "README.md": `# ${theme.name} Theme\n\n${theme.description}\n\nGenerated by ThemeVault`,
        })
        name = `${theme.id}-complete.zip`
        break
    }

    return {
      id: `export-${Date.now()}`,
      name,
      format: options.format,
      content,
      downloadUrl: `data:text/plain;charset=utf-8,${encodeURIComponent(content)}`,
      size: `${Math.round(content.length / 1024)}KB`,
      createdAt: new Date().toISOString(),
    }
  }
}
